[project]
name = "docs-rag"
version = "0.1.0"
description = "RAG experiments for code documentation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain",
    "langchain-chroma",
    "langchain-classic",
    "langchain-community",
    "langchain-core",
    "langchain-ollama",
    "langchain-text-splitters",
    "neo4j",
    "neo4j-graphrag",
    "python-dotenv",
    "rank-bm25",
]
